# Generated by Django 4.1.6 on 2023-05-19 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0003_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='guitar',
            new_name='product',
        ),
    ]
