# Generated by Django 4.1.6 on 2023-05-20 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0004_rename_guitar_basket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guitar',
            name='sale_price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
